name: equibind
channels:
  - pytorch
  - conda-forge
  - defaults
  - dglteam
dependencies:
  - python=3.7
  - pytorch=1.10.2
  - torchvision
  - cudatoolkit=10.2
  - torchaudio
  - dgl-cuda10.2
  - rdkit
  - openbabel
  - biopython
  - rdkit
  - biopandas
  - pot
  - dgllife
  - joblib
  - pyaml
  - icecream
  - matplotlib
  - tensorboard
  - psutil